########################################################################################################################
# thymeleaf
########################################################################################################################
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
########################################################################################################################
# static resources
########################################################################################################################
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
########################################################################################################################
# datasource
########################################################################################################################
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    platform: h2
    driverClassName: org.h2.Driver
    username: sa
    password:
########################################################################################################################
# h2
########################################################################################################################
  h2:
    console:
      enabled: true
