CREATE TABLE IF NOT EXISTS `movie` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `movName` VARCHAR(128) NOT NULL,
  `movYear` INTEGER NOT NULL,
  `movLang` CHAR (50) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO movie (movName, movYear, movLang) VALUES ('Parasite', 2019, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Vertigo', 1958, 'English') ;
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Innocents', 1961, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Lawrence of Arabia', 1962, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Deer Hunter', 1978, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Amadeus', 1984, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Blade Runner', 1982, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Steel Rain', 2017, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Train to Busan', 2016, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('SnowPiercer', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Braveheart', 1995, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Back to the Future', 1985, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spirited Away', 2001, 'Japanese');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Seven Samurai', 1954, 'Japanese');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Avatar', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Beyond the Sea', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Aliens', 1986, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('E.T. The Extra-Terrestrial', 1982, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Prestige', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Slumdog Millionaire', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Don Quixote Cabalga de Nuevo', 1973, 'Spanish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantomas', 1964, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantômas se déchaîne', 1965, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantomas contre Scotland-Yard', 1967, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Deliverance', 1972, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Good Will Hunting', 1997, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Titanic', 1997, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Shawshank Redemption', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Princess Mononoke', 1997, 'Japanese');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Annie Hall', 1977, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Sixth Sense', 1999, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Godfather Part 1', 1972, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Godfather Part 2', 1974, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Godfather Part 3', 1990, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inception',2010, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Intouchables', 2011, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Grace of Monaco', 2014, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Interpreter', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sally: Miracle on The Hudson', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Green Mile', 1999, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Da Vinci Code', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inferno', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Leon: The Professional', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('V for Vendetta', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Little Women', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Darkest Hour', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Fifth Element', 1997, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Count of Monte Cristo', 1998, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Memories of Murder', 2003, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Man from Nowhere', 2010, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Thieves', 2012, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Masquerade', 2012, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Cold Eyes', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Face Reader', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Miracle in Cell No. 7', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Secretly, Greatly', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Architecture 101', 2012, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Casablanca', 1942, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Gone with The Wind', 1939, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Lincoln', 2012, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Good, The Bad, and The Ugly', 1966, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Les Comperes', 1983, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('La Chevre', 1981, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Fugitives', 1986, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Le Jouet', 1976, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi', 1998, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 2', 2000, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 3', 2002, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 4', 2007, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 5', 2018, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Irony of Fate', 1975, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Kidnapping Caucasian Style', 1967, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ivan Vasilievich: Back to The Future', 1973, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Operation Y and Shurik`s Other Adventures', 1965, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Valkyrie', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sherlock Holmes', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sherlock Holmes: A Game of Shadows', 2011, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('My Father and My Son', 2005, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ayla', 2017, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Hunting Season', 2010, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fetih 1453', 2012, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('I Saw The Sun', 2009, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Nizami', 1982, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('If Not That One, Then This One', 1956, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('On Distant Shores', 1958, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Nesimi', 1973, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Foster Mother', 1958, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Last Night of Childhood', 1968, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Bicycle Thieves', 1948, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Rome, Open City', 1945, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Umberto D.', 1952, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Pianist', 2002, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Schindler`s List', 1993, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inglourious Basterds', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Life is Beautiful', 1997, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('In Search of Beethoven', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Chaplin', 1992, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: Modern Times', 1936, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Great Dictator', 1940, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Kid', 1921, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Gold Rush', 1925, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Circus', 1928, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: A Dog`s Life', 1918, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Immigrant', 1917, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Floorwalker', 1916, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: Easy Street', 1917, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Forrest Gump', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Princess Diaries', 2001, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Princess Diaries 2: Royal Engagement', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ella Enchanted', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Devil Wears Prada', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Alica in Wonderland', 2010, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Alice Through the Looking Glass', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Maleficent', 2014, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Maleficent: Mistress of Evil', 2019, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Beauty and The Beast', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Beauty and The Beast',1991,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Oz The Great and Powerful', 2013, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Jungle Book', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Jungle Book',1967,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Jungle Book 2',2003,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Tarzan',1999,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Tarzan and Jane',2002,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Tarzan II',2005,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Princess and The Frog',2009,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Lion King', 2019, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Lion King', 1994,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Lion King 2: Simba`s Pride', 1998,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('A Christmas Carol', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Aladdin', 2019, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Aladdin',1992,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Aladdin and The King of Thieves',1994,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Aladdin: The Return of Jafar',1996,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The BFG', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pete`s Dragon', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Nutcracker and The Four Realms', 2018, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Dolittle', 2020, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Chronicles of Narnia: Prince Caspian', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Chronicles Of Narnia: The Voyage of the Dawn Treader', 2010, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Philosopher`s Stone', 2001, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Chamber of Secrets', 2002, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Prisoner of Azkaban', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Goblet of Fire', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Order of the Phoenix', 2007, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Half-Blood Prince', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Deathly Hallows - Part I', 2010, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Harry Potter and the Deathly Hallows - Part II', 2011, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Intern', 2015, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ocean`s 11', 1960, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ocean`s 11', 2001, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ocean`s 12', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ocean`s 13', 2007, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ocean`s 8', 2018, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Now You See Me', 2013, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Now You Se Me 2', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spider-Man', 2002, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spider-Man 2', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spider-Man 3', 2007, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Amazing Spider-Man', 2012, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Amazing Spider-Man 2', 2014, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spider-Man: Homecoming', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spider-Man: Into the Spider-Verse', 2018, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spider-Man: Far From Home', 2019, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Mummy', 1999, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Mummy Returns', 2001, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Mummy: Tomb of the Dragon Emperor', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Indiana Jones: Raiders of the Lost Ark', 1981, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Indiana Jones and the Temple of Doom', 1984, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Indiana Jones and The Last Crusade', 1989, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Indiana Jones and the Kingdom of the Crystal Skull', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Indiana Jones 5', 2022, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible', 1996, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 2', 2000, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 3', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 4', 2011, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 5', 2015, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 6', 2018, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 7', 2021, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mission: Impossible 8', 2022, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek: The Motion Picture', 1979, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek II: The Wrath of Khan', 1982, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek III: The Search for Spock', 1984, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek IV: The Voyage Home', 1986, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek V: The Final Frontier', 1989, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek VI: The Undiscovered Country', 1991, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek Generations', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek: First Contact', 1996, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek: Insurrection', 1998, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek Nemesis', 2002, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Trek Into Darkness', 2013, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: A New Hope (Episode IV)', 1977, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: The Empire Strikes Back (Episode V)', 1980, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: Return of the Jedi (Episode VI)', 1983, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: The Phantom Menace (Episode I)', 1990, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: Attack of the Clones (Episode II)', 2002, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: Revenge of the Sith (Episode III)', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: The Force Awakens (Episode VII)', 2015, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: The Last Jedi (Episode VIII)', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Star Wars: The Rise of Skywalker (Episode IX)', 2019, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Solo: A Star Wars Story', 2018, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Rise Of The Planet Of The Apes', 2011, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Dawn Of The Planet Of The Apes', 2014, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('War for the Planet of the Apes', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pirates of the Caribbean: Dead Man`s Chest', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pirates of the Caribbean: At World`s End', 2007, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pirates of the Caribbean: On Stranger Tides', 2011, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pirates of the Caribbean: Salazar`s Revenge', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Midnight Runners', 2017, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Assassination ', 2015, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('A Violent Prosecutor', 2016, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Frozen I',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Frozen II',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Gone to Earth',1950,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Over the Moon',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spies in Disguise',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fearless',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Trolls',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Trolls World Tour',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Call of the Wild',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mulan',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mulan',1998,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Alita:Battle Angel',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Klaus',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sonic the Hedgehog',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pocahontas',1995,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Little Mermaid',1989,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Toy story',1995,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Toy story 2',1999,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Toy story 3',2010,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Toy story 4',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Monsters, Inc',2001,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Monsters University',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('A Bug`s Life',1998,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantasia 2000',1999,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Hunchback of Notre Dame',1996,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Rescuers Down Under',1990,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Prince of Egypt',1998,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Brother Bear',2003,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Emperor`s New Groove',2000,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Anastasia',1997,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Bambi',1942,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Sword in the Stone',1963,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('101 Dalmatians',1961,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('101 Dalmatians II: Patch`s London Adventure',2003,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Lady and The Tramp',1955,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Lady and the Tramp II: Scamp`s Adventure',2001,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Foz and The Hound',1981,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Aristocats',1970,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Madagascar',2005,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Madagascar: Escape 2 Africa',2008,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Penguins of Madagascar',2014,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Happy Feet',2006,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Happy Feet Two',2011,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Surf`s Up',2007,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Surf`s Up 2: WaveMania',2017,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Pebble and the Penguin',1995,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Little Polar Bear 2: The Mysterious Island',2005,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Adventures of Lolo the Penguin',1986,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('How to Train Your Dragon',2010,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('How to Train Your Dragon 2',2014,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('How to Train Your Dragon: Homecoming',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Shrek',2001,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Shrek 2',2004,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Shrek the Third',2007,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Shrek Forever After',2010,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Puss in Boots',2011,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Puss in Boots: The Three Diablos',2012,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Secret Life of Pets',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Secret Life of Pets',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Secret of Kells',2009,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix and the Vikings',2006,'French, English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix Versus Caesar',1985,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix: The secret of the Magic Potion',2018,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix in Britain',1986,'French, English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix the Gaul',1967,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix Conquers Amarica',1994,'French, English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix and Obelix vs. Caesar (Astérix et Obélix contre César)',1999,'French, German');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The TwelveTasks of Asterix',1976,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix and the Big Fight',1989,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix and Cleopatra',1968,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix and Obelix: Mission Cleopatra',2002,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix and Obelix -God save Britania',2012,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Asterix bei den Olympischen Speilen',2008,'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Tangled',2010,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pete`s Dragon',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Pete`s Dragon',1977,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Reluctant Dragon',1941,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sleeping Beauty',1959,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mary Poppins',1964,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Mary Poppins Returns',2018,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Christopher Robin',2018,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Onward',2020,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Dumbo',2019,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Brave',2012,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Moana',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Zootropolis',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The House of Magic',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Lorax',2012,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Wild Life',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Croods',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Rio',2011,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Rio 2',2018,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Free Birds',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Grinch',2018,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Coco',2017,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Up',2009,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Bee Movie',2007,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ferdinand',2017,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ratatouille',2007,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Despicable Me',2010,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Despicable Me 2',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Despicable Me 3',2017,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Minions',2015,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Finding Nemo',2003,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Finding Dory',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Storks',2016,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Rising of the Guardians',2012,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inside Out',2015,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Epic',2013,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Home',2015,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Big Hero 6',2014,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Big hero 6: Baymax Returns',2017,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Smallfoot',2018,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Hotel Transylvania',2012,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Hotel Transylvania',2015,'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Hotel Transylvania 3: Summer Vacation',2018,'English');