CREATE TABLE IF NOT EXISTS `movie` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `movName` VARCHAR(128) NOT NULL,
  `movYear` INTEGER NOT NULL,
  `movLang` CHAR (50) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO movie (movName, movYear, movLang) VALUES ('Parasite', 2019, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Vertigo', 1958, 'English') ;
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Innocents', 1961, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Lawrence of Arabia', 1962, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Deer Hunter', 1978, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Amadeus', 1984, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Blade Runner', 1982, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Steel Rain', 2017, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Train to Busan', 2016, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('SnowPiercer', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Braveheart', 1995, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Back to the Future', 1985, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Spirited Away', 2001, 'Japanese');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Seven Samurai', 1954, 'Japanese');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Avatar', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Beyond the Sea', 2004, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Aliens', 1986, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('E.T. The Extra-Terrestrial', 1982, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Prestige', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Slumdog Millionaire', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Don Quixote Cabalga de Nuevo', 1973, 'Spanish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantomas', 1964, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantômas se déchaîne', 1965, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fantomas contre Scotland-Yard', 1967, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Deliverance', 1972, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Good Will Hunting', 1997, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Titanic', 1997, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Shawshank Redemption', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Princess Mononoke', 1997, 'Japanese');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Annie Hall', 1977, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Sixth Sense', 1999, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Godfather Part 1', 1972, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Godfather Part 2', 1974, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Godfather Part 3', 1990, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inception',2010, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Intouchables', 2011, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Grace of Monaco', 2014, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Interpreter', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sally: Miracle on The Hudson', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Green Mile', 1999, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Da Vinci Code', 2006, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inferno', 2016, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Leon: The Professional', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('V for Vendetta', 2005, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Little Women', 1994, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Darkest Hour', 2017, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Fifth Element', 1997, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Count of Monte Cristo', 1998, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Memories of Murder', 2003, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Man from Nowhere', 2010, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Thieves', 2012, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Masquerade', 2012, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Cold Eyes', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Face Reader', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Miracle in Cell No. 7', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Secretly, Greatly', 2013, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Architecture 101', 2012, 'Korean');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Casablanca', 1942, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Gone with The Wind', 1939, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Lincoln', 2012, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Good, The Bad, and The Ugly', 1966, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Les Comperes', 1983, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('La Chevre', 1981, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Fugitives', 1986, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Le Jouet', 1976, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi', 1998, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 2', 2000, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 3', 2002, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 4', 2007, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Taxi 5', 2018, 'French');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Irony of Fate', 1975, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Kidnapping Caucasian Style', 1967, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ivan Vasilievich: Back to The Future', 1973, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Operation Y and Shurik`s Other Adventures', 1965, 'Russian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Valkyrie', 2008, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sherlock Holmes', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Sherlock Holmes: A Game of Shadows', 2011, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('My Father and My Son', 2005, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Ayla', 2017, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Hunting Season', 2010, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Fetih 1453', 2012, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('I Saw The Sun', 2009, 'Turkish');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Nizami', 1982, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('If Not That One, Then This One', 1956, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('On Distant Shores', 1958, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Nesimi', 1973, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Foster Mother', 1958, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Last Night of Childhood', 1968, 'Azerbaijan');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Bicycle Thieves', 1948, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Rome, Open City', 1945, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Umberto D.', 1952, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('The Pianist', 2002, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Schindler`s List', 1993, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Inglourious Basterds', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Life is Beautiful', 1997, 'Italian');
INSERT INTO movie (movName, movYear, movLang) VALUES ('In Search of Beethoven', 2009, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Chaplin', 1992, 'English');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: Modern Times', 1936, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Great Dictator', 1940, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Kid', 1921, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Gold Rush', 1925, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Circus', 1928, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: A Dog`s Life', 1918, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Immigrant', 1917, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: The Floorwalker', 1916, 'Silence Film');
INSERT INTO movie (movName, movYear, movLang) VALUES ('Charlie Chaplin: Easy Street', 1917, 'Silence Film');


